<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'error/404'          => __DIR__ . '/../../view/error/404.phtml',
    'error/index'        => __DIR__ . '/../../view/error/index.phtml',
    'layout/layout'      => __DIR__ . '/../../view/layout/layout.phtml',
    'layout/ajax-layout' => __DIR__ . '/../../view/layout/ajax-layout.phtml',
);
